FROM golang:1.21-alpine AS builder

WORKDIR /app

# Initialize & Install dependencies
COPY main.go .
RUN go mod init tictactoe || true
RUN go get github.com/gorilla/websocket
RUN go get github.com/redis/go-redis/v9
RUN go mod tidy

RUN go build -o main main.go

# Production Image
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .

EXPOSE 8080
CMD ["./main"]